baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "qitmeer Documentation"
theme = "qitmeer-doc"
themesdir = "./themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/HalalChain/docs/edit/master/Document/content/"
  description = "Documentation for Hugo qitmeer-doc"
  author = "Mathieu Cornic"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]


# [Languages]


